name: Deploy

# https://github.com/sitek94/vite-deploy-demo/blob/main/.github/workflows/deploy.yml
# https://raw.githubusercontent.com/sitek94/vite-deploy-demo/main/.github/workflows/deploy.yml

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # paths: src/**
  # pull_request:
  #   branches: [ main ]
  #   paths: src/**    

jobs:
  build:

    # defaults:
    #   run:
    #     working-directory: src
  
    name: Build
    runs-on: ubuntu-latest

    # permissions:
    #   contents: write
    #   # issues: read
    #   # checks: write
    #   # pull-requests: write
    #   # pages: write
    #   # id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: src

      - name: Build project
        run: npm run build
        working-directory: src

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./src/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./src/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/dist
